# create a dictionary of different gcode types
gcode_dict = {
    'G0': 'linear movement in x, y, and z at rate e',
    'G1': 'linear movement in x, y, and z at rate e',
    'G2': 'controlled arc movement',
    'G3': 'controlled arc movement',
    'G4': 'pause for a specific period of time',
    'G10': 'retract filament according to M207',
    'G11': 'unretract filament according to M208',
    'G21': 'set units to mm',
    'G28': 'home all axes/move to origin (with param W means no mesh leveling)',
    'G29': 'detailed z probe (off by default)',
    'G30': 'single z probe',
    'G31': 'dock the z probe sled',
    'G32': 'undock the z probe sled',
    'G75': 'show/print PINDA temperature interpolation',
    'G76': 'PINDA probe temperature calibration',
    'G80': 'mesh based z probe',
    'G81': 'mesh bed leveling status',
    'G82': 'single z probe at current location',
    'G83': 'baby step in z and store in eeprom',
    'G84': 'undo baby step in z',
    'G85': 'pick best baby step',
    'G86': 'disable baby step correction after home',
    'G87': 'enable baby step correction after home',
    'G90': 'switch off relative mode',
    'G91': 'switch on relative mode',
    'G92': 'set positiona t x, y, z',
    'G98': 'activate farm mode',
    'G99': 'deactivate farm mode'
}

# create a dictionary of all mcode commands
mcode_dict = {
    'M17': 'enable all axes',
    'M20': 'SD card file list',
    'M21': 'init SD card',
    'M22': 'release SD card',
    'M23': 'select file',
    'M24': 'start SD print',
    'M26': 'set SD index',
    'M27': 'get SD status',
    'M28': 'start SD write',
    'M29': 'stop SD write',
    'M30': 'delete file',
    'M32': 'select file and start SD print',
    'M928': 'start SD logging',
    'M31': 'report current print time',
    'M42': 'set pin state',
    'M44': 'reset bed skew and offset calibration',
    'M45': 'bed skew offset with manual z up',
    'M46': 'show assigned IP address',
    'M47': 'show end stops dialog on the display',
    'M48': 'z probe repeatability measurement function',
    'M73': 'set/get print progress',
    'M104': 'set hot end temp',
    'M112': 'E-stop',
    'M140': 'set bed temp',
    'M105': 'report temperatures',
    'M155': 'automatically send status',
    'M109': 'wait for extruder temperature',
    'M190': 'wait for bed temperature',
    'M106': 'set fan speed',
    'M107': 'fan off',
    'M80': 'turn on power supply',
    'M81': 'turn off power supply',
    'M82': 'set e axis to absolute mode',
    'M83': 'set e axis to relative mode',
    'M84': 'disable steppers (stop idle hold)',
    'M18': 'disable steppers (disable all steppers)',
    'M85': 'set max inactive time',
    'M86': 'set safety timer expiration time',
    'M92': 'set axis steps per unit',
    'M110': 'set line number',
    'M113': 'get/set host keep-alive interval',
    'M115': 'firmware info',
    'M114': 'get current position',
    'M117': 'display message',
    'M120': 'enable endstops',
    'M121': 'disable endstops',
    'M119': 'get endstop states',
    'M123': 'tachometer value',
    'M150': 'set RGB color',
    'M200': 'set filament diameter',
    'M201': 'set print max acceleration',
    'M203': 'set max feed rate',
    'M204': 'acceleration settings',
    'M205': 'advanced settings',
    'M206': 'set additional homing offsets',
    'M207': 'set firmware retraction',
    'M208': 'set retract recover length',
    'M209': 'enable/disable auto retract',
    'M218': 'set hot end offset',
    'M220': 'set feed rate percentage',
    'M221': 'set extrude factor override percentage',
    'M226': 'wait for pin state',
    'M280': 'get/set servo position',
    'M300': 'play tone',
    'M301': 'set hot end PID',
    'M304': 'set bed PID',
    'M240': 'trigger camera',
    'M303': 'PID autotune',
    'M400': 'wait for all moves to finish',
    'M403': 'set filament type',
    'M500': 'store settings in eeprom',
    'M501': 'read settings from eeprom',
    'M502': 'restore default settings',
    'M503': 'report all settings in memory',
    'M509': 'force language selection',
    'M540': 'abort print on end stop hit',
    'M851': 'set z probe offset',
    'M552': 'set IP address',
    'M600': 'initiate filament change procedure',
    'M601': 'pause print',
    'M602': 'resume print',
    'M603': 'stop print',
    'M860': 'wait for extruder temperature',
    'M861': 'get/set PINDA temperature compensation offsets',
    'M862': 'print checking',
    'M900': 'set linear advance options',
    'M907': 'set digital trimpot motor current in mA using axis codes',
    'M908': 'control digital trimpot directly',
    'M910': 'TMC2130 init',
    'M911': 'set TMC2130 holding current',
    'M912': 'set TMC2130 running current',
    'M913': 'print TMC2130 current',
    'M914': 'set TMC2130 normal mode',
    'M915': 'set TMC2130 silent mode',
    'M916': 'Set TMC2130 Stallguard sensitivity threshold',
    'M917': 'Set TMC2130 PWM amplitude offset',
    'M918': 'Set TMC2130 PWM amplitude gradient',
    'M350': 'set microstepping mode',
    'M351': 'toggle microstep pins',
    'M701': 'load filament',
    'M702': 'unload filament',
    'M999': 'restart after being stopped'
}
